version: '3'
services:
  mobilityhouse-ocpp-central-system:
    build:
      context: .
      dockerfile: central_system/Dockerfile
    container_name: mobilityhouse-ocpp-central-system
    volumes:
      - ./:/mobilityhouse-ocpp-central-system
    working_dir: /mobilityhouse-ocpp-central-system
    expose: 
      - 9000
    ports:
      - 9000:9000
    command: python3 ./central_system/central_system.py
  mobilityhouse-ocpp-charge-point:
    build:
      context: .
      dockerfile: charge_point/Dockerfile
    container_name: mobilityhouse-ocpp-charge-point
    volumes:
      - ./:/mobilityhouse-ocpp-charge-point
    working_dir: /mobilityhouse-ocpp-charge-point
    environment:
      - CSMS_WS_ENDPOINT=ws://${CSMS_WS_ENDPOINT}:9000/CP_1
    command: python3 ./charge_point/charge_point.py
    depends_on: 
      - mobilityhouse-ocpp-central-system